[build]
  base = "app"  # Points to your app directory
  command = "pip install -r requirements.txt && python app.py"
  publish = "public"  # Adjust this based on your app's output (if you have static files)

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200


